feat: Add attachable CloudFront OAI and OAC policies
terraform-aws-modules/terraform-aws-s3-bucket pull request #253
Opened 2023-09-19 13:04 UTC by gw0

## Description

Adds attachable CloudFront Origin Access Identities (deprecated by AWS) and CloudFront Origin Access Identities policies.

## Motivation and Context

An AWS S3 bucket is often connected with an AWS CloudFront distribution and configuring a securely authenticated connection should be trivial. Workarounds such as https://github.com/terraform-aws-modules/terraform-aws-cloudfront/blob/master/examples/complete/main.tf#L294-L327 should not be needed.

## Breaking Changes

None.

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [ ] I have executed `pre-commit run -a` on my pull request

2023-10-20 07:43 UTC, gw0 commented
Is there ay reason why this should not be part of the TF module?

2023-11-20 10:17 UTC, gw0 commented
.

2023-12-22 12:51 UTC, gw0 commented
@antonbabenko This TF module already supports off-the-shelf policies for other AWS services. Why not also support AWS CloudFront?

2024-01-22 14:09 UTC, tculp commented
unstale

2024-01-26 12:18 UTC, antonbabenko requested changes
Looks pretty good. There are a few comments about how to extend it to support read and write ops.

Also, please take a look at the examples in this module AND in the [cloudfront module](https://github.com/terraform-aws-modules/terraform-aws-cloudfront/blob/master/examples/complete/main.tf#L294-L327).

2024-01-26 12:18 UTC, antonbabenko commented on main.tf
> +    actions   = ["s3:ListBucket"]
`s3:ListBucket` doesn't seem to be needed according to the docs - https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html#private-content-restricting-access-to-s3-oai

2024-01-26 12:18 UTC, antonbabenko commented on main.tf
> +    sid = "AWSCloudFrontOAIRead"
Please use the same `sid` as the one you are copying it from the documentation (e.g. `PolicyForCloudFrontPrivateContent`).

2024-01-26 12:18 UTC, antonbabenko commented on main.tf
> +    sid = "AWSCloudFrontOAIRead"
Let's change this statement to support `write` actions as well. Let's use boolean control named `var.attach_cloudfront_oai_policy` and allow parameterization of IAM actions used by OAI via a separate variable:
```
cloudfront_oai_iam_actions = ["s3:GetObject", "s3:PutObject"]
```

The default value is of `cloudfront_oai_iam_actions` is `["s3:GetObject"]`

2024-01-26 12:18 UTC, antonbabenko commented on main.tf
> +data "aws_iam_policy_document" "cloudfront_oai_read_policy" {
```suggestion
data "aws_iam_policy_document" "cloudfront_oai_policy" {
```

2024-01-26 12:18 UTC, antonbabenko commented on main.tf
> +data "aws_iam_policy_document" "cloudfront_oac_read_policy" {
```suggestion
data "aws_iam_policy_document" "cloudfront_oac_policy" {
```

2024-01-26 12:18 UTC, antonbabenko commented on main.tf
> +    actions   = ["s3:GetObject"]
Let's apply the same flexibility in the support for read/write actions as I have described above for OAI.

2024-02-28 21:15 UTC, tculp commented
unstale

2024-05-06 00:03 UTC, closed without merging