Fix typo in description of `access_log_delivery_policy_source_buckets` variable
terraform-aws-modules/terraform-aws-s3-bucket pull request #278
Opened 2024-04-15 17:26 UTC by A-Ashiq

## Description

Candidate for smallest PR in history 😄 just a typo I spotted earlier today when I was using this module.
I promised myself I'd come back and raise a PR for it. Scouts rule and all that!

## Motivation and Context

N/A

## Breaking Changes

None

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

N/A

- [ ] I have executed `pre-commit run -a` on my pull request

2024-04-15 18:01 UTC, antonbabenko requested changes
Almost perfect and small. Could you also update README with the same fix (to fix GH checks)?

2024-04-16 11:21 UTC, A-Ashiq commented
> Almost perfect and small. Could you also update README with the same fix (to fix GH checks)?

Done in 0d504b65335cf62e291b71100f4a0c8908ac30db

2024-04-16 11:24 UTC, antonbabenko approved these changes

2024-04-16 11:24 UTC, merged

2024-04-16 11:25 UTC, antonbabenko commented
This PR is included in version 4.1.2 :tada: